services:
  api:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    build: .
    command: ["rq", "worker", "--url", "${REDIS_URL}", "${RQ_QUEUE}"]
    env_file: .env
    depends_on:
      - redis
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  dbdata:
